-- MySQL Script generated by MySQL Workbench
-- Tue Sep 14 12:47:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupomania_development
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `groupomania_development` ;
CREATE SCHEMA IF NOT EXISTS `groupomania_development` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `groupomania_development` ;

-- -----------------------------------------------------
-- Table `groupomania_development`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania_development`.`Comments` ;

CREATE TABLE IF NOT EXISTS `groupomania_development`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL DEFAULT NULL,
  `postingId` INT NULL DEFAULT NULL,
  `commentId` INT NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comments_ibfk_2` (`postingId` ASC) VISIBLE,
  INDEX `comments_ibfk_3` (`commentId` ASC) VISIBLE,
  INDEX `comments_ibfk_1` (`userId` ASC) VISIBLE,
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `groupomania_development`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`postingId`)
    REFERENCES `groupomania_development`.`Postings` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comments_ibfk_3`
    FOREIGN KEY (`commentId`)
    REFERENCES `groupomania_development`.`Comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupomania_development`.`Likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania_development`.`Likes` ;

CREATE TABLE IF NOT EXISTS `groupomania_development`.`Likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL DEFAULT NULL,
  `postingId` INT NULL DEFAULT NULL,
  `commentId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `likes_ibfk_1_idx` (`userId` ASC) VISIBLE,
  INDEX `likes_ibfk_2_idx` (`postingId` ASC) VISIBLE,
  INDEX `likes_ibfk_3_idx` (`commentId` ASC) VISIBLE,
  CONSTRAINT `likes_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `groupomania_development`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `likes_ibfk_2`
    FOREIGN KEY (`postingId`)
    REFERENCES `groupomania_development`.`Postings` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `likes_ibfk_3`
    FOREIGN KEY (`commentId`)
    REFERENCES `groupomania_development`.`Comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupomania_development`.`Postings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania_development`.`Postings` ;

CREATE TABLE IF NOT EXISTS `groupomania_development`.`Postings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `postings_ibfk_1` (`userId` ASC) VISIBLE,
  CONSTRAINT `postings_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `groupomania_development`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupomania_development`.`Reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania_development`.`Reports` ;

CREATE TABLE IF NOT EXISTS `groupomania_development`.`Reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL DEFAULT NULL,
  `postingId` INT NULL DEFAULT NULL,
  `commentId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `reports_ibfk_1_idx` (`userId` ASC) VISIBLE,
  INDEX `reports_ibfk_2_idx` (`postingId` ASC) VISIBLE,
  INDEX `reports_ibfk_3_idx` (`commentId` ASC) VISIBLE,
  CONSTRAINT `reports_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `groupomania_development`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reports_ibfk_2`
    FOREIGN KEY (`postingId`)
    REFERENCES `groupomania_development`.`Postings` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reports_ibfk_3`
    FOREIGN KEY (`commentId`)
    REFERENCES `groupomania_development`.`Comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupomania_development`.`SequelizeMeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania_development`.`SequelizeMeta` ;

CREATE TABLE IF NOT EXISTS `groupomania_development`.`SequelizeMeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `groupomania_development`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania_development`.`Users` ;

CREATE TABLE IF NOT EXISTS `groupomania_development`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Ppicture` VARCHAR(255) NULL DEFAULT NULL,
  `service` VARCHAR(255) NULL DEFAULT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
